language: cpp
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    packages:
    - libopencv-dev
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../itseez-ws-2016-practice
  - make -j
  - ./bin/test_skeleton
  - ./bin/perf_skeleton --gtest_output=xml:perf_report
  - ../itseez-ws-2016-practice/perf-scripts/summary.py ./perf_report.py
notifications:
  email: false
